export const CodeRelation = {
  NextAction: 'nextAction',
  ClosingBracket: 'closingBracket',
  Key: 'key',
  Event: 'event',
  Variable: 'variable',
  Sound: 'sound',
  Number: 'number',
  Coordinate: 'coordinate',
  Seconds: 'seconds',
  Degree: 'degree',
  Time: 'time',
  Count: 'count',
  LeftNumber: 'leftNumber',
  RightNumber: 'rightNumber',
  Condition: 'condition',
  LeftCondition: 'leftCondition',
  RightCondition: 'rightCondition',
  Actions: 'actions',
  ElseActions: 'elseActions',
  Content: 'content',
  EventName: 'eventName',
  VariableName: 'variableName',
} as const;

export type CodeRelation = (typeof CodeRelation)[keyof typeof CodeRelation];
