export const SymbolEntity = {
  ProgramStart: 'programStart',
  KeyPressed: 'keyPressed',
  EventReceived: 'eventReceived',
  Break: 'break',
  End: 'end',
  Say: 'say',
  SayUntil: 'sayUntil',
  Play: 'play',
  PlayUntil: 'playUntil',
  StopSound: 'stopSound',
  MoveSound: 'moveSound',
  GlideSound: 'glideSound',
  SetPitch: 'setPitch',
  SetVolume: 'setVolume',
  Wait: 'wait',
  DeclareVariable: 'declareVariable',
  SetVariable: 'setVariable',
  ChangeVariable: 'changeVariable',
  SendEvent: 'sendEvent',
  IfThen: 'ifThen',
  IfElse: 'ifElse',
  Repeat: 'repeat',
  RepeatFor: 'repeatFor',
  RepeatUntil: 'repeatUntil',
  IsGreater: 'isGreater',
  IsLess: 'isLess',
  Equals: 'equals',
  And: 'and',
  Or: 'or',
  Not: 'not',
  NumericLiteral: 'numericLiteral',
  Plus: 'plus',
  Minus: 'minus',
  Times: 'times',
  DividedBy: 'dividedBy',
  Remainder: 'remainder',
  RandomNumber: 'randomNumber',
  StringLiteral: 'stringLiteral'
} as const;

export type SymbolEntity = (typeof SymbolEntity)[keyof typeof SymbolEntity];
